name: Implicit Animations Workshop
type: flutter
steps:
  - name: Welcome to the Implicit Animations Workshop
    directory: intro
    has_solution: false
  - name: Convert into a Stateful Widget
    directory: step_01
    has_solution: true